namespace SpriteKind {
    export const IGRIS = SpriteKind.create()
    export const heart = SpriteKind.create()
    export const icemonarch = SpriteKind.create()
    export const icebeam = SpriteKind.create()
}
sprites.onDestroyed(SpriteKind.heart, function (sprite) {
    sprites.destroyAllSpritesOfKind(SpriteKind.heart, effects.spray, 500)
})
controller.up.onEvent(ControllerButtonEvent.Pressed, function () {
    animation.runImageAnimation(
    mySprite,
    [img`
        . . . . . . f f f f . . . . . . 
        . . . . f f e e e e f f . . . . 
        . . . f e e e f f e e e f . . . 
        . . f f f f f 2 2 f f f f f . . 
        . . f f e 2 e 2 2 e 2 e f f . . 
        . . f e 2 f 2 f f 2 f 2 e f . . 
        . . f f f 2 2 e e 2 2 f f f . . 
        . f f e f 2 f e e f 2 f e f f . 
        . f e e f f e e e e f e e e f . 
        . . f e e e e e e e e e e f . . 
        . . . f e e e e e e e e f . . . 
        . . e 4 f f f f f f f f 4 e . . 
        . . 4 d f 2 2 2 2 2 2 f d 4 . . 
        . . 4 4 f 4 4 4 4 4 4 f 4 4 . . 
        . . . . . f f f f f f . . . . . 
        . . . . . f f . . f f . . . . . 
        `,img`
        . . . . . . . . . . . . . . . . 
        . . . . . . f f f f . . . . . . 
        . . . . f f e e e e f f . . . . 
        . . . f e e e f f e e e f . . . 
        . . . f f f f 2 2 f f f f . . . 
        . . f f e 2 e 2 2 e 2 e f f . . 
        . . f e 2 f 2 f f f 2 f e f . . 
        . . f f f 2 f e e 2 2 f f f . . 
        . . f e 2 f f e e 2 f e e f . . 
        . f f e f f e e e f e e e f f . 
        . f f e e e e e e e e e e f f . 
        . . . f e e e e e e e e f . . . 
        . . . e f f f f f f f f 4 e . . 
        . . . 4 f 2 2 2 2 2 e d d 4 . . 
        . . . e f f f f f f e e 4 . . . 
        . . . . f f f . . . . . . . . . 
        `,img`
        . . . . . . f f f f . . . . . . 
        . . . . f f e e e e f f . . . . 
        . . . f e e e f f e e e f . . . 
        . . f f f f f 2 2 f f f f f . . 
        . . f f e 2 e 2 2 e 2 e f f . . 
        . . f e 2 f 2 f f 2 f 2 e f . . 
        . . f f f 2 2 e e 2 2 f f f . . 
        . f f e f 2 f e e f 2 f e f f . 
        . f e e f f e e e e f e e e f . 
        . . f e e e e e e e e e e f . . 
        . . . f e e e e e e e e f . . . 
        . . e 4 f f f f f f f f 4 e . . 
        . . 4 d f 2 2 2 2 2 2 f d 4 . . 
        . . 4 4 f 4 4 4 4 4 4 f 4 4 . . 
        . . . . . f f f f f f . . . . . 
        . . . . . f f . . f f . . . . . 
        `,img`
        . . . . . . . . . . . . . . . . 
        . . . . . . f f f f . . . . . . 
        . . . . f f e e e e f f . . . . 
        . . . f e e e f f e e e f . . . 
        . . . f f f f 2 2 f f f f . . . 
        . . f f e 2 e 2 2 e 2 e f f . . 
        . . f e f 2 f f f 2 f 2 e f . . 
        . . f f f 2 2 e e f 2 f f f . . 
        . . f e e f 2 e e f f 2 e f . . 
        . f f e e e f e e e f f e f f . 
        . f f e e e e e e e e e e f f . 
        . . . f e e e e e e e e f . . . 
        . . e 4 f f f f f f f f e . . . 
        . . 4 d d e 2 2 2 2 2 f 4 . . . 
        . . . 4 e e f f f f f f e . . . 
        . . . . . . . . . f f f . . . . 
        `],
    250,
    true
    )
})
controller.left.onEvent(ControllerButtonEvent.Pressed, function () {
    animation.runImageAnimation(
    mySprite,
    [img`
        . . . . f f f f f f . . . . . . 
        . . . f 2 f e e e e f f . . . . 
        . . f 2 2 2 f e e e e f f . . . 
        . . f e e e e f f e e e f . . . 
        . f e 2 2 2 2 e e f f f f . . . 
        . f 2 e f f f f 2 2 2 e f . . . 
        . f f f e e e f f f f f f f . . 
        . f e e 4 4 f b e 4 4 e f f . . 
        . . f e d d f 1 4 d 4 e e f . . 
        . . . f d d d d 4 e e e f . . . 
        . . . f e 4 4 4 e e f f . . . . 
        . . . f 2 2 2 e d d 4 . . . . . 
        . . . f 2 2 2 e d d e . . . . . 
        . . . f 5 5 4 f e e f . . . . . 
        . . . . f f f f f f . . . . . . 
        . . . . . . f f f . . . . . . . 
        `,img`
        . . . . . . . . . . . . . . . . 
        . . . . f f f f f f . . . . . . 
        . . . f 2 f e e e e f f . . . . 
        . . f 2 2 2 f e e e e f f . . . 
        . . f e e e e f f e e e f . . . 
        . f e 2 2 2 2 e e f f f f . . . 
        . f 2 e f f f f 2 2 2 e f . . . 
        . f f f e e e f f f f f f f . . 
        . f e e 4 4 f b e 4 4 e f f . . 
        . . f e d d f 1 4 d 4 e e f . . 
        . . . f d d d e e e e e f . . . 
        . . . f e 4 e d d 4 f . . . . . 
        . . . f 2 2 e d d e f . . . . . 
        . . f f 5 5 f e e f f f . . . . 
        . . f f f f f f f f f f . . . . 
        . . . f f f . . . f f . . . . . 
        `,img`
        . . . . f f f f f f . . . . . . 
        . . . f 2 f e e e e f f . . . . 
        . . f 2 2 2 f e e e e f f . . . 
        . . f e e e e f f e e e f . . . 
        . f e 2 2 2 2 e e f f f f . . . 
        . f 2 e f f f f 2 2 2 e f . . . 
        . f f f e e e f f f f f f f . . 
        . f e e 4 4 f b e 4 4 e f f . . 
        . . f e d d f 1 4 d 4 e e f . . 
        . . . f d d d d 4 e e e f . . . 
        . . . f e 4 4 4 e e f f . . . . 
        . . . f 2 2 2 e d d 4 . . . . . 
        . . . f 2 2 2 e d d e . . . . . 
        . . . f 5 5 4 f e e f . . . . . 
        . . . . f f f f f f . . . . . . 
        . . . . . . f f f . . . . . . . 
        `,img`
        . . . . . . . . . . . . . . . . 
        . . . . f f f f f f . . . . . . 
        . . . f 2 f e e e e f f . . . . 
        . . f 2 2 2 f e e e e f f . . . 
        . . f e e e e f f e e e f . . . 
        . f e 2 2 2 2 e e f f f f . . . 
        . f 2 e f f f f 2 2 2 e f . . . 
        . f f f e e e f f f f f f f . . 
        . f e e 4 4 f b e 4 4 e f f . . 
        . . f e d d f 1 4 d 4 e e f . . 
        . . . f d d d d 4 e e e f . . . 
        . . . f e 4 4 4 e d d 4 . . . . 
        . . . f 2 2 2 2 e d d e . . . . 
        . . f f 5 5 4 4 f e e f . . . . 
        . . f f f f f f f f f f . . . . 
        . . . f f f . . . f f . . . . . 
        `],
    250,
    true
    )
})
controller.right.onEvent(ControllerButtonEvent.Pressed, function () {
    animation.runImageAnimation(
    mySprite,
    [img`
        . . . . . . f f f f f f . . . . 
        . . . . f f e e e e f 2 f . . . 
        . . . f f e e e e f 2 2 2 f . . 
        . . . f e e e f f e e e e f . . 
        . . . f f f f e e 2 2 2 2 e f . 
        . . . f e 2 2 2 f f f f e 2 f . 
        . . f f f f f f f e e e f f f . 
        . . f f e 4 4 e b f 4 4 e e f . 
        . . f e e 4 d 4 1 f d d e f . . 
        . . . f e e e 4 d d d d f . . . 
        . . . . f f e e 4 4 4 e f . . . 
        . . . . . 4 d d e 2 2 2 f . . . 
        . . . . . e d d e 2 2 2 f . . . 
        . . . . . f e e f 4 5 5 f . . . 
        . . . . . . f f f f f f . . . . 
        . . . . . . . f f f . . . . . . 
        `,img`
        . . . . . . . . . . . . . . . . 
        . . . . . . f f f f f f . . . . 
        . . . . f f e e e e f 2 f . . . 
        . . . f f e e e e f 2 2 2 f . . 
        . . . f e e e f f e e e e f . . 
        . . . f f f f e e 2 2 2 2 e f . 
        . . . f e 2 2 2 f f f f e 2 f . 
        . . f f f f f f f e e e f f f . 
        . . f f e 4 4 e b f 4 4 e e f . 
        . . f e e 4 d 4 1 f d d e f . . 
        . . . f e e e e e d d d f . . . 
        . . . . . f 4 d d e 4 e f . . . 
        . . . . . f e d d e 2 2 f . . . 
        . . . . f f f e e f 5 5 f f . . 
        . . . . f f f f f f f f f f . . 
        . . . . . f f . . . f f f . . . 
        `,img`
        . . . . . . f f f f f f . . . . 
        . . . . f f e e e e f 2 f . . . 
        . . . f f e e e e f 2 2 2 f . . 
        . . . f e e e f f e e e e f . . 
        . . . f f f f e e 2 2 2 2 e f . 
        . . . f e 2 2 2 f f f f e 2 f . 
        . . f f f f f f f e e e f f f . 
        . . f f e 4 4 e b f 4 4 e e f . 
        . . f e e 4 d 4 1 f d d e f . . 
        . . . f e e e 4 d d d d f . . . 
        . . . . f f e e 4 4 4 e f . . . 
        . . . . . 4 d d e 2 2 2 f . . . 
        . . . . . e d d e 2 2 2 f . . . 
        . . . . . f e e f 4 5 5 f . . . 
        . . . . . . f f f f f f . . . . 
        . . . . . . . f f f . . . . . . 
        `,img`
        . . . . . . . . . . . . . . . . 
        . . . . . . f f f f f f . . . . 
        . . . . f f e e e e f 2 f . . . 
        . . . f f e e e e f 2 2 2 f . . 
        . . . f e e e f f e e e e f . . 
        . . . f f f f e e 2 2 2 2 e f . 
        . . . f e 2 2 2 f f f f e 2 f . 
        . . f f f f f f f e e e f f f . 
        . . f f e 4 4 e b f 4 4 e e f . 
        . . f e e 4 d 4 1 f d d e f . . 
        . . . f e e e 4 d d d d f . . . 
        . . . . 4 d d e 4 4 4 e f . . . 
        . . . . e d d e 2 2 2 2 f . . . 
        . . . . f e e f 4 4 5 5 f f . . 
        . . . . f f f f f f f f f f . . 
        . . . . . f f . . . f f f . . . 
        `],
    250,
    true
    )
})
controller.down.onEvent(ControllerButtonEvent.Pressed, function () {
    animation.runImageAnimation(
    mySprite,
    [img`
        . . . . . . f f f f . . . . . . 
        . . . . f f f 2 2 f f f . . . . 
        . . . f f f 2 2 2 2 f f f . . . 
        . . f f f e e e e e e f f f . . 
        . . f f e 2 2 2 2 2 2 e e f . . 
        . . f e 2 f f f f f f 2 e f . . 
        . . f f f f e e e e f f f f . . 
        . f f e f b f 4 4 f b f e f f . 
        . f e e 4 1 f d d f 1 4 e e f . 
        . . f e e d d d d d d e e f . . 
        . . . f e e 4 4 4 4 e e f . . . 
        . . e 4 f 2 2 2 2 2 2 f 4 e . . 
        . . 4 d f 2 2 2 2 2 2 f d 4 . . 
        . . 4 4 f 4 4 5 5 4 4 f 4 4 . . 
        . . . . . f f f f f f . . . . . 
        . . . . . f f . . f f . . . . . 
        `,img`
        . . . . . . . . . . . . . . . . 
        . . . . . . f f f f . . . . . . 
        . . . . f f f 2 2 f f f . . . . 
        . . . f f f 2 2 2 2 f f f . . . 
        . . f f f e e e e e e f f f . . 
        . . f f e 2 2 2 2 2 2 e e f . . 
        . f f e 2 f f f f f f 2 e f f . 
        . f f f f f e e e e f f f f f . 
        . . f e f b f 4 4 f b f e f . . 
        . . f e 4 1 f d d f 1 4 e f . . 
        . . . f e 4 d d d d 4 e f e . . 
        . . f e f 2 2 2 2 e d d 4 e . . 
        . . e 4 f 2 2 2 2 e d d e . . . 
        . . . . f 4 4 5 5 f e e . . . . 
        . . . . f f f f f f f . . . . . 
        . . . . f f f . . . . . . . . . 
        `,img`
        . . . . . . f f f f . . . . . . 
        . . . . f f f 2 2 f f f . . . . 
        . . . f f f 2 2 2 2 f f f . . . 
        . . f f f e e e e e e f f f . . 
        . . f f e 2 2 2 2 2 2 e e f . . 
        . . f e 2 f f f f f f 2 e f . . 
        . . f f f f e e e e f f f f . . 
        . f f e f b f 4 4 f b f e f f . 
        . f e e 4 1 f d d f 1 4 e e f . 
        . . f e e d d d d d d e e f . . 
        . . . f e e 4 4 4 4 e e f . . . 
        . . e 4 f 2 2 2 2 2 2 f 4 e . . 
        . . 4 d f 2 2 2 2 2 2 f d 4 . . 
        . . 4 4 f 4 4 5 5 4 4 f 4 4 . . 
        . . . . . f f f f f f . . . . . 
        . . . . . f f . . f f . . . . . 
        `,img`
        . . . . . . . . . . . . . . . . 
        . . . . . . f f f f . . . . . . 
        . . . . f f f 2 2 f f f . . . . 
        . . . f f f 2 2 2 2 f f f . . . 
        . . f f f e e e e e e f f f . . 
        . . f e e 2 2 2 2 2 2 e f f . . 
        . f f e 2 f f f f f f 2 e f f . 
        . f f f f f e e e e f f f f f . 
        . . f e f b f 4 4 f b f e f . . 
        . . f e 4 1 f d d f 1 4 e f . . 
        . . e f e 4 d d d d 4 e f . . . 
        . . e 4 d d e 2 2 2 2 f e f . . 
        . . . e d d e 2 2 2 2 f 4 e . . 
        . . . . e e f 5 5 4 4 f . . . . 
        . . . . . f f f f f f f . . . . 
        . . . . . . . . . f f f . . . . 
        `],
    250,
    true
    )
})
sprites.onOverlap(SpriteKind.Projectile, SpriteKind.icebeam, function (sprite, otherSprite) {
    sprite.destroy()
    otherSprite.destroy()
})
info.onLifeZero(function () {
    mySprite.destroy()
    game.over(false)
})
sprites.onOverlap(SpriteKind.heart, SpriteKind.Player, function (sprite, otherSprite) {
    sprite.destroy()
    info.changeLifeBy(1)
    info.changeScoreBy(1)
})
sprites.onOverlap(SpriteKind.Projectile, SpriteKind.Enemy, function (sprite, otherSprite) {
    sprite.destroy()
    otherSprite.destroy()
    info.changeScoreBy(1)
})
let projectile: Sprite = null
let mySprite2: Sprite = null
let projectile2: Sprite = null
let ice_monarch: Sprite = null
let monster: Sprite = null
let mySprite: Sprite = null
let IGRIS_COOL_DOWN = 0
mySprite = sprites.create(img`
    ........................
    ....ffffff..............
    ..ffeeeef2f.............
    .ffeeeef222f............
    .feeeffeeeef...cc.......
    .ffffee2222ef.cdc.......
    .fe222ffffe2fcddc.......
    fffffffeeeffcddc........
    ffe44ebf44ecddc.........
    fee4d41fddecdc..........
    .feee4dddedccc..........
    ..ffee44e4dde...........
    ...f222244ee............
    ...f2222e2f.............
    ...f444455f.............
    ....ffffff..............
    .....fff................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    `, SpriteKind.Player)
tiles.setTilemap(tilemap`level2`)
scene.cameraFollowSprite(mySprite)
info.setLife(5)
forever(function () {
    if (info.score() < 5) {
        for (let index = 0; index < 2; index++) {
            monster = sprites.create(img`
                . . f f f . . . . . . . . f f f 
                . f f c c . . . . . . f c b b c 
                f f c c . . . . . . f c b b c . 
                f c f c . . . . . . f b c c c . 
                f f f c c . c c . f c b b c c . 
                f f c 3 c c 3 c c f b c b b c . 
                f f b 3 b c 3 b c f b c c b c . 
                . c 1 b b b 1 b c b b c c c . . 
                . c 1 b b b 1 b b c c c c . . . 
                c b b b b b b b b b c c . . . . 
                c b 1 f f 1 c b b b b f . . . . 
                f f 1 f f 1 f b b b b f c . . . 
                f f 2 2 2 2 f b b b b f c c . . 
                . f 2 2 2 2 b b b b c f . . . . 
                . . f b b b b b b c f . . . . . 
                . . . f f f f f f f . . . . . . 
                `, SpriteKind.Enemy)
            monster.setPosition(randint(0, 300), randint(0, 300))
            animation.runImageAnimation(
            monster,
            [img`
                . . f f f . . . . . . . . f f f 
                . f f c c . . . . . . f c b b c 
                f f c c . . . . . . f c b b c . 
                f c f c . . . . . . f b c c c . 
                f f f c c . c c . f c b b c c . 
                f f c 3 c c 3 c c f b c b b c . 
                f f b 3 b c 3 b c f b c c b c . 
                . c 1 b b b 1 b c b b c c c . . 
                . c 1 b b b 1 b b c c c c . . . 
                c b b b b b b b b b c c . . . . 
                c b 1 f f 1 c b b b b f . . . . 
                f f 1 f f 1 f b b b b f c . . . 
                f f 2 2 2 2 f b b b b f c c . . 
                . f 2 2 2 2 b b b b c f . . . . 
                . . f b b b b b b c f . . . . . 
                . . . f f f f f f f . . . . . . 
                `,img`
                . . f f f . . . . . . . . . . . 
                f f f c c . . . . . . . . f f f 
                f f c c c . c c . . . f c b b c 
                f f c 3 c c 3 c c f f b b b c . 
                f f c 3 b c 3 b c f b b c c c . 
                f c b b b b b b c f b c b c c . 
                c c 1 b b b 1 b c b b c b b c . 
                c b b b b b b b b b c c c b c . 
                c b 1 f f 1 c b b c c c c c . . 
                c f 1 f f 1 f b b b b f c . . . 
                f f f f f f f b b b b f c . . . 
                f f 2 2 2 2 f b b b b f c c . . 
                . f 2 2 2 2 2 b b b c f . . . . 
                . . f 2 2 2 b b b c f . . . . . 
                . . . f f f f f f f . . . . . . 
                . . . . . . . . . . . . . . . . 
                `,img`
                . . . . . . . . . . . . . . . . 
                . . . . . . . . . . . . . . . . 
                . . . c c . c c . . . . . . . . 
                . . f 3 c c 3 c c c . . . . . . 
                . f c 3 b c 3 b c c c . . . . . 
                f c b b b b b b b b f f . . . . 
                c c 1 b b b 1 b b b f f . . . . 
                c b b b b b b b b c f f f . . . 
                c b 1 f f 1 c b b f f f f . . . 
                f f 1 f f 1 f b c c b b b . . . 
                f f f f f f f b f c c c c . . . 
                f f 2 2 2 2 f b f b b c c c . . 
                . f 2 2 2 2 2 b c c b b c . . . 
                . . f 2 2 2 b f f c c b b c . . 
                . . . f f f f f f f c c c c c . 
                . . . . . . . . . . . . c c c c 
                `,img`
                . f f f . . . . . . . . f f f . 
                f f c . . . . . . . f c b b c . 
                f c c . . . . . . f c b b c . . 
                c f . . . . . . . f b c c c . . 
                c f f . . . . . f f b b c c . . 
                f f f c c . c c f b c b b c . . 
                f f f c c c c c f b c c b c . . 
                . f c 3 c c 3 b c b c c c . . . 
                . c b 3 b c 3 b b c c c c . . . 
                c c b b b b b b b b c c . . . . 
                c 1 1 b b b 1 1 b b b f c . . . 
                f b b b b b b b b b b f c c . . 
                f b c b b b c b b b b f . . . . 
                . f 1 f f f 1 b b b c f . . . . 
                . . f b b b b b b c f . . . . . 
                . . . f f f f f f f . . . . . . 
                `],
            500,
            true
            )
            monster.follow(mySprite, 50)
        }
        pause(2000)
    } else if (info.score() >= 5 && info.score() < 30) {
        info.changeScoreBy(30)
        pause(1000)
        tiles.setCurrentTilemap(tilemap`level3`)
        ice_monarch = sprites.create(img`
            . . . . . . 5 . 5 . . . . . . . 
            . . . . . f 5 5 5 f f . . . . . 
            . . . . f 1 5 2 5 1 6 f . . . . 
            . . . f 1 6 6 6 6 6 1 6 f . . . 
            . . . f 6 6 f f f f 6 1 f . . . 
            . . . f 6 f f d d f f 6 f . . . 
            . . f 6 f d f d d f d f 6 f . . 
            . . f 6 f d 3 d d 3 d f 6 f . . 
            . . f 6 6 f d d d d f 6 6 f . . 
            . f 6 6 f 3 f f f f 3 f 6 6 f . 
            . . f f d 3 5 3 3 5 3 3 f f . . 
            . . f d f f 3 5 5 3 f d f . . . 
            . . . f f 3 3 3 3 3 f d f . . . 
            . . . f 3 3 5 3 3 5 3 f f . . . 
            . . . f f f f f f f f f . . . . 
            . . . . . f f . . . . . . . . . 
            `, SpriteKind.icemonarch)
        ice_monarch.setPosition(200, 200)
        scaling.scaleToPixels(ice_monarch, 32, ScaleDirection.Horizontally, ScaleAnchor.Middle)
        scaling.scaleToPixels(ice_monarch, 32, ScaleDirection.Vertically, ScaleAnchor.Middle)
        animation.runImageAnimation(
        ice_monarch,
        [img`
            . . . . . . 8 . 8 . . . . . . . 
            . . . . . f 8 8 8 f . . . . . . 
            . . . . f 9 6 8 8 9 f . . . . . 
            . . . f 9 9 9 9 1 9 9 f . . . . 
            . . . f 9 9 9 9 9 1 9 f . . . . 
            . . . f d 7 d 9 9 9 1 f . . . . 
            . . . f d 7 d 9 9 9 9 f f . . . 
            . . . f d 8 d d 9 9 9 f 6 f . . 
            . . . . f d d d f f 9 f f . . . 
            . . . . . f f 9 6 f 9 9 9 f . . 
            . . . . f 9 6 6 f f f f f . . . 
            . . . . f 6 6 f d f . . . . . . 
            . . . . . f 6 f d f . . . . . . 
            . . . . f 6 9 6 f d f . . . . . 
            . . . . f f 6 6 f f . . . . . . 
            . . . . . . f f f . . . . . . . 
            `,img`
            . . . . . . . . . . . . . . . . 
            . . . . . . . 8 . 8 . . . . . . 
            . . . . . . f 8 8 8 f . . . . . 
            . . . . . f 9 6 8 8 9 f . . . . 
            . . . . f 9 9 9 9 1 9 9 f . . . 
            . . . . f 9 9 9 9 9 1 9 f . . . 
            . . . . f d 7 d 9 9 9 1 f . . . 
            . . . . f d 7 d 9 9 9 9 f f . . 
            . . . . f d 8 d d 9 9 9 f 9 f . 
            . . . . . f d d d f f 9 f f . . 
            . . . . . . f f 6 6 f f 9 9 f . 
            . . . . . f d d d d f f f f . . 
            . . . . . f d d d f 6 f . . . . 
            . . . . . . f f f d 9 6 f . . . 
            . . . . . f f f 6 6 f f . . . . 
            . . . . . f f f f f f f . . . . 
            `,img`
            . . . . . . . . . . . . . . . . 
            . . . . . . . 8 . 8 . . . . . . 
            . . . . . . f 8 8 8 f . . . . . 
            . . . . . f 9 6 8 8 9 f . . . . 
            . . . . f 9 9 9 9 1 9 9 f . . . 
            . . . . f 9 9 9 9 9 1 9 f . . . 
            . . . . f d 7 d 9 9 9 1 f . . . 
            . . . . f d 7 d 9 9 9 9 f f . . 
            . . . . f d 8 d d 9 9 9 f 9 f . 
            . . . . . f d d d f f 9 f f . . 
            . . . . . . f f 6 6 f f 9 9 f . 
            . . . . . f 9 6 6 d d f f f . . 
            . . . . . f 6 6 6 f d d f . . . 
            . . . . . . f 6 9 f f f . . . . 
            . . . . . f 6 6 6 6 f . . . . . 
            . . . . . . f f f f f . . . . . 
            `],
        500,
        true
        )
    } else {
        for (let index = 0; index < 20; index++) {
            for (let index = 0; index < 5; index++) {
                ice_monarch.y += -2
                pause(100)
            }
            projectile2 = sprites.createProjectileFromSprite(img`
                . . . . . . . . . . . . . . . . 
                . . . . . . . . . . . . . . . . 
                . . . . . . . . . . . . . . . . 
                . . . . . . . . . . . . . . . . 
                . . . 8 8 8 8 . . . . . . . . . 
                . . 8 9 9 9 9 8 8 . . . . . . . 
                . . 9 9 9 9 9 9 6 6 8 8 . . . . 
                . . 9 9 9 9 9 9 9 9 6 6 6 6 . . 
                . . 9 9 9 9 9 9 9 9 9 9 9 9 . . 
                . . 9 9 9 9 9 9 9 6 8 8 6 6 . . 
                . . 8 9 9 9 9 6 8 8 . . . . . . 
                . . . 8 8 8 8 . . . . . . . . . 
                . . . . . . . . . . . . . . . . 
                . . . . . . . . . . . . . . . . 
                . . . . . . . . . . . . . . . . 
                . . . . . . . . . . . . . . . . 
                `, ice_monarch, -100, 0)
            scaling.scaleByPixels(projectile2, 10, ScaleDirection.Horizontally, ScaleAnchor.Middle)
            scaling.scaleByPixels(projectile2, 10, ScaleDirection.Vertically, ScaleAnchor.Middle)
            projectile2.setKind(SpriteKind.icebeam)
        }
        for (let index = 0; index < 20; index++) {
            for (let index = 0; index < 5; index++) {
                ice_monarch.y += 2
                pause(100)
            }
            projectile2 = sprites.createProjectileFromSprite(img`
                . . . . . . . . . . . . . . . . 
                . . . . . . . . . . . . . . . . 
                . . . . . . . . . . . . . . . . 
                . . . . . . . . . . . . . . . . 
                . . . 8 8 8 8 . . . . . . . . . 
                . . 8 9 9 9 9 8 8 . . . . . . . 
                . . 9 9 9 9 9 9 6 6 8 8 . . . . 
                . . 9 9 9 9 9 9 9 9 6 6 6 6 . . 
                . . 9 9 9 9 9 9 9 9 9 9 9 9 . . 
                . . 9 9 9 9 9 9 9 6 8 8 6 6 . . 
                . . 8 9 9 9 9 6 8 8 . . . . . . 
                . . . 8 8 8 8 . . . . . . . . . 
                . . . . . . . . . . . . . . . . 
                . . . . . . . . . . . . . . . . 
                . . . . . . . . . . . . . . . . 
                . . . . . . . . . . . . . . . . 
                `, ice_monarch, -100, 0)
            scaling.scaleByPixels(projectile2, 10, ScaleDirection.Horizontally, ScaleAnchor.Middle)
            scaling.scaleByPixels(projectile2, 10, ScaleDirection.Vertically, ScaleAnchor.Middle)
            projectile2.setKind(SpriteKind.icebeam)
        }
        ice_monarch.y += -100
        for (let index = 0; index < 20; index++) {
            animation.runImageAnimation(
            ice_monarch,
            [img`
                . . . . . . 8 . 8 . . . . . . . 
                . . . . . f 8 8 8 f f . . . . . 
                . . . . f 1 8 6 8 1 9 f . . . . 
                . . . f 1 9 9 9 9 9 1 9 f . . . 
                . . . f 9 9 f f f f 9 1 f . . . 
                . . . f 9 f 7 d d 7 f 9 f . . . 
                . . f 9 f d 7 d d 7 d f 9 f . . 
                . . f 9 f d 8 d d 8 d f 9 f . . 
                . . f 9 9 f d d d d f 9 9 f . . 
                . f 9 9 f 6 f f f f 6 f 9 9 f . 
                . . f f d 6 9 6 6 9 6 d f f . . 
                . . f d d f 6 9 9 6 f d d f . . 
                . . . f f 6 6 6 6 6 6 f f . . . 
                . . . f 6 6 9 6 6 9 6 6 f . . . 
                . . . f f f f f f f f f f . . . 
                . . . . . f f . . f f . . . . . 
                `,img`
                . . . . . . 8 . 8 . . . . . . . 
                . . . . . f 8 8 8 f f . . . . . 
                . . . . f 1 8 6 8 1 9 f . . . . 
                . . . f 1 9 9 9 9 9 1 9 f . . . 
                . . . f 9 9 f f f f 9 1 f . . . 
                . . . f 9 f 7 d d 7 f 9 f . . . 
                . . f 9 f d 7 d d 7 d f 9 f . . 
                . . f 9 f d 8 d d 8 d f 9 f . . 
                . . f 9 9 f d d d d f 9 9 f . . 
                . f 9 9 f 6 f f f f 6 f 9 9 f . 
                . . f f 6 6 9 6 6 9 6 d f f . . 
                . . . f d f 6 9 9 6 f f d f . . 
                . . . f d f 6 6 6 6 6 f f . . . 
                . . . f f 6 9 6 6 9 6 6 f . . . 
                . . . . f f f f f f f f f . . . 
                . . . . . . . . . f f . . . . . 
                `,img`
                . . . . . . 8 . 8 . . . . . . . 
                . . . . . f 8 8 8 f f . . . . . 
                . . . . f 1 8 6 8 1 9 f . . . . 
                . . . f 1 9 9 9 9 9 1 9 f . . . 
                . . . f 9 9 f f f f 9 1 f . . . 
                . . . f 9 f 7 d d 7 f 9 f . . . 
                . . f 9 f d 7 d d 7 d f 9 f . . 
                . . f 9 f d 8 d d 8 d f 9 f . . 
                . . f 9 9 f d d d d f 9 9 f . . 
                . f 9 9 f 6 f f f f 6 f 9 9 f . 
                . . f f d 6 9 6 6 9 6 6 f f . . 
                . . f d f f 6 9 9 6 f d f . . . 
                . . . f f 6 6 6 6 6 f d f . . . 
                . . . f 6 6 9 6 6 9 6 f f . . . 
                . . . f f f f f f f f f . . . . 
                . . . . . f f . . . . . . . . . 
                `],
            500,
            true
            )
        }
    }
})
forever(function () {
    if (controller.B.isPressed()) {
        mySprite2 = sprites.create(img`
            ........................
            ........................
            ........................
            ........................
            ..........ffff..........
            ........ff1111ff........
            .......fb111111bf.......
            .......f11111111f.......
            ......fd11111111df......
            ......fd11111111df......
            ......fddd1111dddf......
            ......fbdbfddfbdbf......
            ......fcdcf11fcdcf......
            .......fb111111bf.......
            ......fffcdb1bdffff.....
            ....fc111cbfbfc111cf....
            ....f1b1b1ffff1b1b1f....
            ....fbfbffffffbfbfbf....
            .........ffffff.........
            ...........fff..........
            ........................
            ........................
            ........................
            ........................
            `, SpriteKind.IGRIS)
        mySprite2.setPosition(scene.cameraProperty(CameraProperty.X), scene.cameraProperty(CameraProperty.Y) / 1)
        animation.runImageAnimation(
        mySprite,
        [img`
            ........................
            .....ffff...............
            ...fff22fff.............
            ..fff2222fff............
            .fffeeeeeefff...........
            .ffe222222eef...........
            .fe2ffffff2ef...........
            .ffffeeeeffff...........
            ffefbf44fbfeff..........
            fee41fddf14eef..........
            .ffffdddddeef...........
            fddddf444eef............
            fbbbbf2222f4e...........
            fbbbbf2222fd4...........
            .fccf45544f44...........
            ..ffffffff..............
            ....ff..ff..............
            ........................
            ................3.......
            ........................
            ........................
            ........................
            ........................
            ........................
            `,img`
            ........................
            ........................
            .......ff...............
            .....ff22ff.............
            ...fff2222fff...........
            ..fff222222fff..........
            ..fff222222fff..........
            ..feeeeeeeeeeff.........
            .ffe22222222eff.........
            .fffffeeeefffff.........
            fdfefbf44fbfeff.........
            fbfe41fddf14ef..........
            fbffe4dddd4efe..........
            fcfef22222f4e...........
            .ff4f44554f4e...........
            ....ffffffdde...........
            .....ffffedde...........
            ..........ee............
            .........ccc............
            ........cc1cc...........
            .........c1c............
            .........c1c............
            .........c1c............
            .........c1c............
            `],
        50,
        false
        )
        if (controller.right.isPressed()) {
            animation.runImageAnimation(
            mySprite2,
            [img`
                ........................
                ........................
                ........................
                ..........ffff..........
                ........ff1111ff........
                .......fb111111bf.......
                ......fbd1111111f.......
                ......fdd1111111df......
                ......fddd111111df......
                ......fdddddd111df......
                ......fdddddd111df......
                ......fbddddddd1df......
                ......ffbbddbfd1df......
                .......fcbbdcfddbf......
                .......fffbddccffff.....
                .......ffffcfbbb1bcf....
                ......ffffffffcd1b1f....
                ...ffffffffff..fdfdf....
                .....ffffff.....f.f.....
                ........................
                ........................
                ........................
                ........................
                ........................
                `,img`
                ........................
                ........................
                ........................
                ........................
                .........fffff..........
                .......ffb1111ff........
                ......fb1111111bf.......
                ......f111111111f.......
                .....ffff1111111df......
                ....fb111c1dd111df......
                ....ffb1b1fdcf11bf......
                .....ffbfbfb11111f......
                ......ffffcfdb1b1f......
                .......fcccfcfbfbf......
                ........ffffffffff......
                .........ffffff.........
                .........ffffff.........
                .....f..fffffff.........
                .....fffffffff..........
                ......fffffff...........
                ........................
                ........................
                ........................
                ........................
                `],
            50,
            true
            )
            pause(100)
            for (let index = 0; index < 8; index++) {
                projectile = sprites.createProjectileFromSprite(img`
                    . . f f f f . . 
                    . f 8 7 7 8 f . 
                    f 8 f 8 8 f 8 f 
                    f 7 8 7 f 8 7 f 
                    f 7 8 f 7 8 7 f 
                    f 8 f 8 8 f 8 f 
                    . f 8 7 7 8 f . 
                    . . f f f f . . 
                    `, mySprite2, 200, 0)
                pause(100)
            }
            pause(10)
            mySprite2.destroy()
            info.startCountdown(15)
            mySprite2.destroy()
            pause(15000)
        } else if (controller.left.isPressed()) {
            animation.runImageAnimation(
            mySprite2,
            [img`
                ........................
                ........................
                ........................
                ........................
                ..........fffff.........
                ........ff1111bff.......
                .......fb1111111bf......
                .......f111111111f......
                ......fd1111111ffff.....
                ......fd111dd1c111bf....
                ......fb11fcdf1b1bff....
                ......f11111bfbfbff.....
                ......f1b1bdfcffff......
                ......fbfbfcfcccf.......
                ......ffffffffff........
                .........ffffff.........
                .........ffffff.........
                .........fffffff..f.....
                ..........fffffffff.....
                ...........fffffff......
                ........................
                ........................
                ........................
                ........................
                `,img`
                ........................
                ........................
                ........................
                ..........ffff..........
                ........ff1111ff........
                .......fb111111bf.......
                .......f1111111dbf......
                ......fd1111111ddf......
                ......fd111111dddf......
                ......fd111ddddddf......
                ......fd111ddddddf......
                ......fd1dddddddbf......
                ......fd1dfbddbbff......
                ......fbddfcdbbcf.......
                .....ffffccddbfff.......
                ....fcb1bbbfcffff.......
                ....f1b1dcffffffff......
                ....fdfdf..ffffffffff...
                .....f.f.....ffffff.....
                ........................
                ........................
                ........................
                ........................
                ........................
                `],
            50,
            true
            )
            pause(100)
            for (let index = 0; index < 8; index++) {
                projectile = sprites.createProjectileFromSprite(img`
                    . . f f f f . . 
                    . f 8 7 7 8 f . 
                    f 8 f 8 8 f 8 f 
                    f 7 8 7 f 8 7 f 
                    f 7 8 f 7 8 7 f 
                    f 8 f 8 8 f 8 f 
                    . f 8 7 7 8 f . 
                    . . f f f f . . 
                    `, mySprite2, -200, 0)
                pause(100)
            }
            pause(10)
            mySprite2.destroy()
            info.startCountdown(15)
            mySprite2.destroy()
            pause(15000)
        } else {
            animation.runImageAnimation(
            mySprite2,
            [img`
                ........................
                ........................
                ........................
                ........................
                ........................
                ..........ffff..........
                ........ff1111ff........
                .......fb111111bf.......
                .....fffc1111111f.......
                ...fc111cd1111111f......
                ...f1b1b1b1111dddf......
                ...fbfbffcf11fcddf......
                ......fcf111111bbf......
                .......ccbdb1b1fcf......
                .......fffbfbfdff.......
                ........ffffffff........
                ........fffffffffff.....
                .........fffffc111cf....
                .........fffff1b1b1f....
                ..........ffffbfbfbf....
                ...........ffff.........
                ........................
                ........................
                ........................
                `,img`
                ........................
                ........................
                ........................
                ........................
                ........................
                ..........ffff..........
                ........ff1111ff........
                .......fb111111bf.......
                .......f11111111f.......
                ......fd11111111df......
                ....7.fd11111111df......
                ...7..fd11111111df......
                ...7..fd11111111df......
                ...7..fddd1111dddff.....
                ...77.fbdbfddfbdbfcf....
                ...777fcdcf11fcdcfbf....
                ....77fffbdb1bdffcf.....
                ....fcb1bcffffff........
                ....f1c1c1ffffff........
                ....fdfdfdfffff.........
                .....f.f.f..............
                ........................
                ........................
                ........................
                `,img`
                ........................
                ........................
                ........................
                ........................
                ..........ffff..........
                ........ff1111ff........
                .......fb111111bf.......
                .......f11111111f.......
                ......fd111111111f......
                ......fd11111111df......
                ......fd11111111df......
                ......fcdd1111ddcff.....
                .......fbcf11fcbfbbf....
                .......ffbdb1bdffff.....
                ........fcbfbfdf........
                ........ffffffff........
                ......ffffffffff........
                .....fcb1bcffff.........
                ......ffbff.............
                ........................
                ........................
                ........................
                ........................
                ........................
                `,img`
                ........................
                ........................
                ........................
                ........................
                ..........ffff..........
                ........ff1111ff........
                .......fb111111bf.......
                .......f11111111f.......
                ......fd11111111df......
                ......fdd111111ddf......
                ......fbdd1111dddf......
                ......fcdbfddfbdbf......
                .......fbcf11fcbfff.....
                .......ffb1111bcfbcf....
                ........fcdb1bdfbbbf....
                .......ffffffffffcf.....
                .....fcb1bcfffff........
                .....f1b1b1ffff.........
                ......ffbff.............
                ........................
                ........................
                ........................
                ........................
                ........................
                `],
            50,
            true
            )
            pause(100)
            for (let index = 0; index < 4; index++) {
                projectile = sprites.createProjectileFromSprite(img`
                    . . f f f f . . 
                    . f 8 7 7 8 f . 
                    f 8 f 8 8 f 8 f 
                    f 7 8 7 f 8 7 f 
                    f 7 8 f 7 8 7 f 
                    f 8 f 8 8 f 8 f 
                    . f 8 7 7 8 f . 
                    . . f f f f . . 
                    `, mySprite2, 0, 200)
                projectile = sprites.createProjectileFromSprite(img`
                    . . f f f f . . 
                    . f 8 7 7 8 f . 
                    f 8 f 8 8 f 8 f 
                    f 7 8 7 f 8 7 f 
                    f 7 8 f 7 8 7 f 
                    f 8 f 8 8 f 8 f 
                    . f 8 7 7 8 f . 
                    . . f f f f . . 
                    `, mySprite2, 0, -200)
                pause(150)
            }
            pause(10)
            mySprite2.destroy()
            info.startCountdown(15)
            mySprite2.destroy()
            pause(15000)
        }
    }
})
forever(function () {
    if (controller.left.isPressed()) {
        mySprite.x += -2
    }
    if (controller.right.isPressed()) {
        mySprite.x += 2
    }
    if (controller.down.isPressed()) {
        mySprite.y += 2
    }
    if (controller.up.isPressed()) {
        mySprite.y += -2
    }
})
forever(function () {
	
})
forever(function () {
	
})
forever(function () {
    music.playMelody("C D C E C F C E ", 120)
    music.playMelody("D F C D E D C E ", 120)
    music.playMelody("C D C E C F C E ", 120)
    music.playMelody("D F C D E D C E ", 120)
    music.playMelody("C E G F E G A F ", 120)
    music.playMelody("F E D G D F E D ", 120)
})
forever(function () {
    if (controller.A.isPressed()) {
        if (controller.left.isPressed()) {
            animation.runImageAnimation(
            mySprite,
            [img`
                ..............ffffff....
                .............f2feeeeff..
                ............f222feeeeff.
                .......cc...feeeeffeeef.
                .......cdc.fe2222eeffff.
                .......cddcf2effff222ef.
                ........cddcffeeefffffff
                .........cddce44fbe44eff
                ..........cdceddf14d4eef
                ..........cccdeddd4eeef.
                ...........edd4e44eeff..
                ............ee442222f...
                .............f2e2222f...
                .............f554444f...
                ..............ffffff....
                ................fff.....
                ........................
                ........................
                ........................
                ........................
                ........................
                ........................
                ........................
                ........................
                `,img`
                ........................
                ..............fff.......
                .............f2fffff....
                ...........ff22eeeeeff..
                ..........ff222eeeeeeff.
                ..........feeeefffeeeef.
                .........fe2222eeefffff.
                .........f2efffff222efff
                ..cc.....fffeeefffffffff
                ..cdcc...fee44fbbe44efef
                ..ccddcc..feddfbb4d4eef.
                ....cdddceefddddd4eeef..
                .....ccdcddee2222222f...
                ......cccdd44e544444f...
                .........eeeeffffffff...
                .............ff...fff...
                ........................
                ........................
                ........................
                ........................
                ........................
                ........................
                ........................
                ........................
                `,img`
                ...............ff.......
                .............ff2ffff....
                ............ff2feeeeff..
                ...........ff22feeeeeff.
                ...........feeeeffeeeef.
                ..........fe2222eefffff.
                ..........f2effff222efff
                ..........fffeeeffffffff
                ..........fee44fbe44efef
                ...........feddfb4d4eef.
                ..........c.eeddd4eeef..
                ....ccccccceddee2222f...
                .....dddddcedd44e444f...
                ......ccccc.eeeefffff...
                ..........c...ffffffff..
                ...............ff..fff..
                ........................
                ........................
                ........................
                ........................
                ........................
                ........................
                ........................
                ........................
                `,img`
                ..............ffffff....
                .............f2feeeeff..
                ............f222feeeeff.
                ............feeeeffeeef.
                ...........fe2222eeffff.
                ...........f2effff222ef.
                ...........fffeeefffffff
                ...........fee44fbe44eff
                ............feddf14d4eef
                .............fdddd4eeef.
                .............fe444eddf..
                .............ccc22eddf..
                .............cdc22fee...
                ............cddc4444f...
                ...........cddcfffff....
                ..........cddc..fff.....
                ..........cdc...........
                ..........cc............
                ........................
                ........................
                ........................
                ........................
                ........................
                ........................
                `],
            50,
            false
            )
            projectile = sprites.createProjectileFromSprite(img`
                . . f f f f . . 
                . f a c c a f . 
                f a f a a f a f 
                f c a c f a c f 
                f c a f c a c f 
                f a f a a f a f 
                . f a c c a f . 
                . . f f f f . . 
                `, mySprite, -200, 0)
            pause(420)
        } else if (controller.right.isPressed()) {
            animation.runImageAnimation(
            mySprite,
            [img`
                ....ffffff..............
                ..ffeeeef2f.............
                .ffeeeef222f............
                .feeeffeeeef...cc.......
                .ffffee2222ef.cdc.......
                .fe222ffffe2fcddc.......
                fffffffeeeffcddc........
                ffe44ebf44ecddc.........
                fee4d41fddecdc..........
                .feee4dddedccc..........
                ..ffee44e4dde...........
                ...f222244ee............
                ...f2222e2f.............
                ...f444455f.............
                ....ffffff..............
                .....fff................
                ........................
                ........................
                ........................
                ........................
                ........................
                ........................
                ........................
                ........................
                `,img`
                ........................
                .......fff..............
                ....fffff2f.............
                ..ffeeeee22ff...........
                .ffeeeeee222ff..........
                .feeeefffeeeef..........
                .fffffeee2222ef.........
                fffe222fffffe2f.........
                fffffffffeeefff.....cc..
                fefe44ebbf44eef...ccdc..
                .fee4d4bbfddef..ccddcc..
                ..feee4dddddfeecdddc....
                ...f2222222eeddcdcc.....
                ...f444445e44ddccc......
                ...ffffffffeeee.........
                ...fff...ff.............
                ........................
                ........................
                ........................
                ........................
                ........................
                ........................
                ........................
                ........................
                `,img`
                .......ff...............
                ....ffff2ff.............
                ..ffeeeef2ff............
                .ffeeeeef22ff...........
                .feeeeffeeeef...........
                .fffffee2222ef..........
                fffe222ffffe2f..........
                ffffffffeeefff..........
                fefe44ebf44eef..........
                .fee4d4bfddef...........
                ..feee4dddee.c..........
                ...f2222eeddeccccccc....
                ...f444e44ddecddddd.....
                ...fffffeeee.ccccc......
                ..ffffffff...c..........
                ..fff..ff...............
                ........................
                ........................
                ........................
                ........................
                ........................
                ........................
                ........................
                ........................
                `,img`
                ....ffffff..............
                ..ffeeeef2f.............
                .ffeeeef222f............
                .feeeffeeeef............
                .ffffee2222ef...........
                .fe222ffffe2f...........
                fffffffeeefff...........
                ffe44ebf44eef...........
                fee4d41fddef............
                .feee4ddddf.............
                ..fdde444ef.............
                ..fdde22ccc.............
                ...eef22cdc.............
                ...f4444cddc............
                ....fffffcddc...........
                .....fff..cddc..........
                ...........cdc..........
                ............cc..........
                ........................
                ........................
                ........................
                ........................
                ........................
                ........................
                `],
            50,
            false
            )
            projectile = sprites.createProjectileFromSprite(img`
                . . f f f f . . 
                . f a c c a f . 
                f a f a a f a f 
                f c a c f a c f 
                f c a f c a c f 
                f a f a a f a f 
                . f a c c a f . 
                . . f f f f . . 
                `, mySprite, 200, 0)
            pause(420)
        } else {
            animation.runImageAnimation(
            mySprite,
            [img`
                ........................
                .....ffff...............
                ...fff22fff.............
                ..fff2222fff............
                .fffeeeeeefff...........
                .ffe222222eef...........
                .fe2ffffff2ef...........
                .ffffeeeeffff...........
                ffefbf44fbfeff..........
                fee41fddf14eef..........
                .ffffdddddeef...........
                fddddf444eef............
                fbbbbf2222f4e...........
                fbbbbf2222fd4...........
                .fccf45544f44...........
                ..ffffffff..............
                ....ff..ff..............
                ........................
                ........................
                ........................
                ........................
                ........................
                ........................
                ........................
                `,img`
                ........................
                ......ffff..............
                ....fff22fff............
                ...fff2222fff...........
                ..fffeeeeeefff..........
                ..ffe222222eef..........
                ..fe2ffffff2ef..........
                ..ffffeeeeffff..........
                .ffefbf44fbfeff.........
                .fee41fddf14eef.........
                fdfeeddddd4eff..........
                fbffee444edd4e..........
                fbf4f2222edde...........
                fcf.f22cccee............
                .ff.f44cdc4f............
                ....fffddcff............
                .....fddcff.............
                ....cddc................
                ....cdc.................
                ....cc..................
                ........................
                ........................
                ........................
                ........................
                `,img`
                ........................
                ........................
                .......ff...............
                .....ff22ff.............
                ...fff2222fff...........
                ..fff222222fff..........
                ..fff222222fff..........
                ..feeeeeeeeeeff.........
                .ffe22222222eff.........
                .fffffeeeefffff.........
                fdfefbf44fbfeff.........
                fbfe41fddf14ef..........
                fbffe4dddd4efe..........
                fcfef22222f4e...........
                .ff4f44554f4e...........
                ....ffffffdde...........
                .....ffffedde...........
                ..........ee............
                .........ccc............
                ........cc1cc...........
                .........c1c............
                .........c1c............
                .........c1c............
                .........c1c............
                `,img`
                ......ffff..............
                ....fff22fff............
                ...fff2222fff...........
                ..fffeeeeeefff..........
                ..ffe222222eef..........
                ..fe2ffffff2ef..........
                ..ffffeeeeffff......ccc.
                .ffefbf44fbfeff....cddc.
                .ffefbf44fbfeff...cddc..
                .fee4dddddd4eef.ccddc...
                fdfeeddddd4eeffecddc....
                fbffee4444ee4fddccc.....
                fbf4f222222f1edde.......
                fcf.f222222f44ee........
                .ff.f445544f............
                ....ffffffff............
                .....ff..ff.............
                ........................
                ........................
                ........................
                ........................
                ........................
                ........................
                ........................
                `],
            50,
            false
            )
            projectile = sprites.createProjectileFromSprite(img`
                . . f f f f . . 
                . f a c c a f . 
                f a f a a f a f 
                f c a c f a c f 
                f c a f c a c f 
                f a f a a f a f 
                . f a c c a f . 
                . . f f f f . . 
                `, mySprite, 0, 200)
            projectile = sprites.createProjectileFromSprite(img`
                . . f f f f . . 
                . f a c c a f . 
                f a f a a f a f 
                f c a c f a c f 
                f c a f c a c f 
                f a f a a f a f 
                . f a c c a f . 
                . . f f f f . . 
                `, mySprite, 0, -200)
            pause(420)
        }
    }
})
